{% set name = "dash-labs" %}
{% set version = "0.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dash-labs-{{ version }}.tar.gz
    sha256: ca8fc8be369aa6cd20a3016764e12a0d8b66a5caf549b3b001a5981eead5eccb
  - path: requirements.txt

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - dash >=1.18.1
    - dash-bootstrap-components >=0.11.1
    - dataclasses >=0.8
    - python >=3.6

test:
  imports:
    - dash_labs
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/plotly/dash-labs
  summary: Experimental enhancements for potential inclusion in Dash
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - asford
